//// Warning: Do not modify!
//// This file (EnumerationUniqueKey_Name.cs) has been auto-generated by PALMS Entity Generation Tool on '12 January 2012' at '16:40:13'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.UniqueKeys
{
	[Serializable]
	public partial class EnumerationUniqueKey_Name : EntityKey<EnumerationEntity>
	{
		#region Enums

		public enum Field
		{
			EnumerationName
			, EnumerationType
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public string enumerationName;
		public string enumerationType;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.EnumerationName:
					return enumerationName;
				case Field.EnumerationType:
					return enumerationType;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.EnumerationName:
					return typeof(string);
				case Field.EnumerationType:
					return typeof(string);
			}

			return null;
		}

		public override EnumerationEntity GetBlankEntityWithKey()
		{
			return new EnumerationEntity()
			{
				enumerationName = enumerationName
				, enumerationType = enumerationType
			};
		}

		public override string GetClassName()
		{
			return "EnumerationUniqueKey_Name";
		}

		#endregion Overriding / Public Members
	}
}
