//// Warning: Do not modify!
//// This file (PackUniqueKey_OriginalNo_ReferenceNo.cs) has been auto-generated by PALMS Entity Generation Tool on '10 October 2012' at '11:08:06'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.UniqueKeys
{
	[Serializable]
	public partial class PackUniqueKey_OriginalNo_ReferenceNo : EntityKey<PackEntity>
	{
		#region Enums

		public enum Field
		{
			CostBucketID
			, OriginalPackNo
			, PrimaryCompanyID
			, ReferenceNo
			, WarehouseID
			, WarehousePrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? costBucketID;
		public string originalPackNo;
		public int? primaryCompanyID;
		public string referenceNo;
		public int? warehouseID;
		public int? warehousePrimaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return costBucketID;
				case Field.OriginalPackNo:
					return originalPackNo;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.ReferenceNo:
					return referenceNo;
				case Field.WarehouseID:
					return warehouseID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return typeof(int?);
				case Field.OriginalPackNo:
					return typeof(string);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.ReferenceNo:
					return typeof(string);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override PackEntity GetBlankEntityWithKey()
		{
			return new PackEntity()
			{
				costBucketID = costBucketID
				, originalPackNo = originalPackNo
				, primaryCompanyID = primaryCompanyID
				, referenceNo = referenceNo
				, warehouseID = warehouseID
				, warehousePrimaryCompanyID = warehousePrimaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "PackUniqueKey_OriginalNo_ReferenceNo";
		}

		#endregion Overriding / Public Members
	}
}
