//// Warning: Do not modify!
//// This file (TransactionTypeUniqueKey_Name.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, July 26, 2016' at '11:33:26 AM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.UniqueKeys
{
	[Serializable]
	public partial class TransactionTypeUniqueKey_Name : EntityKey<TransactionTypeEntity>
	{
		#region Enums

		public enum Field
		{
			TransactionTypeName
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public string transactionTypeName;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.TransactionTypeName:
					return transactionTypeName;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.TransactionTypeName:
					return typeof(string);
			}

			return null;
		}

		public override TransactionTypeEntity GetBlankEntityWithKey()
		{
			return new TransactionTypeEntity()
			{
				transactionTypeName = transactionTypeName
			};
		}

		public override string GetClassName()
		{
			return "TransactionTypeUniqueKey_Name";
		}

		#endregion Overriding / Public Members
	}
}
