//// Warning: Do not modify!
//// This file (PartUOMMappingEntity.cs) has been auto-generated by PALMS Entity Generation Tool on 'Wednesday, September 23, 2015' at '4:55:22 PM'
//// If modification is required, consider 'partial class'.

using System;
using System.Collections;
using System.Collections.Generic;
using Technoforte.PALMS.Entities.Views.PrimaryKeys;
using Technoforte.PALMS.Entities.Views.UniqueKeys;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views
{
	[Serializable]
	public partial class PartUOMMappingEntity : Entity
	{
		#region Enums

		public new enum Field
		{
			PrimaryCompanyID
			, PartID
			, UOMID
			, MultiplicationFactorToConvertToStorageUOM
			, Barcode
			, CreatedBy_PalmsUserLoginName
			, ModifiedBy_PalmsUserLoginName
			, PartID_PartCode
			, PartID_PartName
			, PrimaryCompanyID_DocumentNoPrefix
			, PrimaryCompanyID_PrimaryCompanyCode
			, PrimaryCompanyID_PrimaryCompanyName
			, UOMID_UOMCode
			, UOMID_UOMName
			
			, _FieldCount
		}

		public enum UniqueKey
		{
			Barcode
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? partID;
		public int? uOMID;
		public decimal? multiplicationFactorToConvertToStorageUOM;
		public string barcode;
		public string createdBy_PalmsUserLoginName;
		public string modifiedBy_PalmsUserLoginName;
		public string partID_PartCode;
		public string partID_PartName;
		public string primaryCompanyID_DocumentNoPrefix;
		public string primaryCompanyID_PrimaryCompanyCode;
		public string primaryCompanyID_PrimaryCompanyName;
		public string uOMID_UOMCode;
		public string uOMID_UOMName;

		#endregion Members

		#region Overriding / Public Members

		public override IEntityKey<Entity> GetPrimaryKey()
		{
			return (IEntityKey<Entity>)new PartUOMMappingPrimaryKey()
			{
				partID = (int)partID
				, primaryCompanyID = (int)primaryCompanyID
				, uOMID = (int)uOMID
			};
		}

		public override IEntityKey<Entity> GetBlankPrimaryKey()
		{
			return (IEntityKey<Entity>)new PartUOMMappingPrimaryKey();
		}

		public override IEntityKey<Entity> GetUniqueKey(string uniqueKey)
		{
			if (uniqueKey == "")
			{
				uniqueKey = "Barcode";
			}

			return (IEntityKey<Entity>)GetUniqueKey((UniqueKey)Enum.Parse(typeof(UniqueKey), uniqueKey, false));
		}

		public EntityKey<PartUOMMappingEntity> GetUniqueKey(UniqueKey uniqueKey)
		{
			switch (uniqueKey)
			{
				case UniqueKey.Barcode:
					return new PartUOMMappingUniqueKey_Barcode()
					{
						barcode = (string)barcode
						, primaryCompanyID = (int?)primaryCompanyID
					};
			}

			return null;
		}

		public override IEntityKey<Entity> GetBlankUniqueKey(string uniqueKey)
		{
			if (uniqueKey == "")
			{
				uniqueKey = "Barcode";
			}

			return (IEntityKey<Entity>)GetBlankUniqueKey((UniqueKey)Enum.Parse(typeof(UniqueKey), uniqueKey, false));
		}

		public EntityKey<PartUOMMappingEntity> GetBlankUniqueKey(UniqueKey uniqueKey)
		{
			switch (uniqueKey)
			{
				case UniqueKey.Barcode:
					return new PartUOMMappingUniqueKey_Barcode();
			}

			return null;
		}

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.PartID:
					return partID;
				case Field.UOMID:
					return uOMID;
				case Field.MultiplicationFactorToConvertToStorageUOM:
					return multiplicationFactorToConvertToStorageUOM;
				case Field.Barcode:
					return barcode;
				case Field.CreatedBy_PalmsUserLoginName:
					return createdBy_PalmsUserLoginName;
				case Field.ModifiedBy_PalmsUserLoginName:
					return modifiedBy_PalmsUserLoginName;
				case Field.PartID_PartCode:
					return partID_PartCode;
				case Field.PartID_PartName:
					return partID_PartName;
				case Field.PrimaryCompanyID_DocumentNoPrefix:
					return primaryCompanyID_DocumentNoPrefix;
				case Field.PrimaryCompanyID_PrimaryCompanyCode:
					return primaryCompanyID_PrimaryCompanyCode;
				case Field.PrimaryCompanyID_PrimaryCompanyName:
					return primaryCompanyID_PrimaryCompanyName;
				case Field.UOMID_UOMCode:
					return uOMID_UOMCode;
				case Field.UOMID_UOMName:
					return uOMID_UOMName;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.PartID:
					return typeof(int?);
				case Field.UOMID:
					return typeof(int?);
				case Field.MultiplicationFactorToConvertToStorageUOM:
					return typeof(decimal?);
				case Field.Barcode:
					return typeof(string);
				case Field.CreatedBy_PalmsUserLoginName:
					return typeof(string);
				case Field.ModifiedBy_PalmsUserLoginName:
					return typeof(string);
				case Field.PartID_PartCode:
					return typeof(string);
				case Field.PartID_PartName:
					return typeof(string);
				case Field.PrimaryCompanyID_DocumentNoPrefix:
					return typeof(string);
				case Field.PrimaryCompanyID_PrimaryCompanyCode:
					return typeof(string);
				case Field.PrimaryCompanyID_PrimaryCompanyName:
					return typeof(string);
				case Field.UOMID_UOMCode:
					return typeof(string);
				case Field.UOMID_UOMName:
					return typeof(string);

			}
			return null;
		}

		public override void SetValue(int field, bool? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, bool? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, long? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, long? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, int? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, int? value)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					primaryCompanyID = value;
					break;
				case Field.PartID:
					partID = value;
					break;
				case Field.UOMID:
					uOMID = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, short? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, short? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, byte? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, byte? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, BitArray value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, BitArray value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, float? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, float? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, double? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, double? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, decimal? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, decimal? value)
		{
			switch (field)
			{
				case Field.MultiplicationFactorToConvertToStorageUOM:
					multiplicationFactorToConvertToStorageUOM = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, char? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, char? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, string value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, string value)
		{
			switch (field)
			{
				case Field.Barcode:
					barcode = value;
					break;
				case Field.CreatedBy_PalmsUserLoginName:
					createdBy_PalmsUserLoginName = value;
					break;
				case Field.ModifiedBy_PalmsUserLoginName:
					modifiedBy_PalmsUserLoginName = value;
					break;
				case Field.PartID_PartCode:
					partID_PartCode = value;
					break;
				case Field.PartID_PartName:
					partID_PartName = value;
					break;
				case Field.PrimaryCompanyID_DocumentNoPrefix:
					primaryCompanyID_DocumentNoPrefix = value;
					break;
				case Field.PrimaryCompanyID_PrimaryCompanyCode:
					primaryCompanyID_PrimaryCompanyCode = value;
					break;
				case Field.PrimaryCompanyID_PrimaryCompanyName:
					primaryCompanyID_PrimaryCompanyName = value;
					break;
				case Field.UOMID_UOMCode:
					uOMID_UOMCode = value;
					break;
				case Field.UOMID_UOMName:
					uOMID_UOMName = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, DateTime? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, DateTime? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, Guid? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, Guid? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override bool IsIdentity(int field)
		{
			return false;
		}

		#endregion Overriding / Public Members
	}
}
