//// Warning: Do not modify!
//// This file (PartPickingFromHandheldLiftActionEntity.cs) has been auto-generated by PALMS Entity Generation Tool on '17 April 2013' at '17:20:23'
//// If modification is required, consider 'partial class'.

using System;
using System.Collections;
using System.Collections.Generic;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Actions
{
	[Serializable]
	public partial class PartPickingFromHandheldLiftActionEntity : Entity
	{
		#region Enums

		public new enum Field
		{
			WarehouseID
			, PrimaryCompanyID
			, WarehousePrimaryCompanyID
			, CostBucketID
			, StockChangeInstructionID
			, ReferenceLineNo
			, IsDamaged
			, LiftedQuantityInStorageUOM
			, ActualBatchID
			, MoveableLocationID
			, ReferenceID
			, ActualSerialNo
			, ActualPartBatchNo
			, ActualExpiryDate
			, ActualManufacturingDate
			, ActualFromLocationID
			, ActualFromPackID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? warehouseID;
		public int? primaryCompanyID;
		public int? warehousePrimaryCompanyID;
		public int? costBucketID;
		public int? stockChangeInstructionID;
		public int? referenceLineNo;
		public bool? isDamaged;
		public decimal? liftedQuantityInStorageUOM;
		public int? actualBatchID;
		public int? moveableLocationID;
		public int? referenceID;
		public string actualSerialNo;
		public string actualPartBatchNo;
		public DateTime? actualExpiryDate;
		public DateTime? actualManufacturingDate;
		public int? actualFromLocationID;
		public int? actualFromPackID;

		#endregion Members

		#region Overriding / Public Members


		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return warehouseID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.StockChangeInstructionID:
					return stockChangeInstructionID;
				case Field.ReferenceLineNo:
					return referenceLineNo;
				case Field.IsDamaged:
					return isDamaged;
				case Field.LiftedQuantityInStorageUOM:
					return liftedQuantityInStorageUOM;
				case Field.ActualBatchID:
					return actualBatchID;
				case Field.MoveableLocationID:
					return moveableLocationID;
				case Field.ReferenceID:
					return referenceID;
				case Field.ActualSerialNo:
					return actualSerialNo;
				case Field.ActualPartBatchNo:
					return actualPartBatchNo;
				case Field.ActualExpiryDate:
					return actualExpiryDate;
				case Field.ActualManufacturingDate:
					return actualManufacturingDate;
				case Field.ActualFromLocationID:
					return actualFromLocationID;
				case Field.ActualFromPackID:
					return actualFromPackID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.StockChangeInstructionID:
					return typeof(int?);
				case Field.ReferenceLineNo:
					return typeof(int?);
				case Field.IsDamaged:
					return typeof(bool?);
				case Field.LiftedQuantityInStorageUOM:
					return typeof(decimal?);
				case Field.ActualBatchID:
					return typeof(int?);
				case Field.MoveableLocationID:
					return typeof(int?);
				case Field.ReferenceID:
					return typeof(int?);
				case Field.ActualSerialNo:
					return typeof(string);
				case Field.ActualPartBatchNo:
					return typeof(string);
				case Field.ActualExpiryDate:
					return typeof(DateTime?);
				case Field.ActualManufacturingDate:
					return typeof(DateTime?);
				case Field.ActualFromLocationID:
					return typeof(int?);
				case Field.ActualFromPackID:
					return typeof(int?);

			}
			return null;
		}

		public override void SetValue(int field, bool? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, bool? value)
		{
			switch (field)
			{
				case Field.IsDamaged:
					isDamaged = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, long? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, long? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, int? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, int? value)
		{
			switch (field)
			{
				case Field.WarehouseID:
					warehouseID = value;
					break;
				case Field.PrimaryCompanyID:
					primaryCompanyID = value;
					break;
				case Field.WarehousePrimaryCompanyID:
					warehousePrimaryCompanyID = value;
					break;
				case Field.CostBucketID:
					costBucketID = value;
					break;
				case Field.StockChangeInstructionID:
					stockChangeInstructionID = value;
					break;
				case Field.ReferenceLineNo:
					referenceLineNo = value;
					break;
				case Field.ActualBatchID:
					actualBatchID = value;
					break;
				case Field.MoveableLocationID:
					moveableLocationID = value;
					break;
				case Field.ReferenceID:
					referenceID = value;
					break;
				case Field.ActualFromLocationID:
					actualFromLocationID = value;
					break;
				case Field.ActualFromPackID:
					actualFromPackID = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, short? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, short? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, byte? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, byte? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, BitArray value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, BitArray value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, float? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, float? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, double? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, double? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, decimal? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, decimal? value)
		{
			switch (field)
			{
				case Field.LiftedQuantityInStorageUOM:
					liftedQuantityInStorageUOM = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, char? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, char? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, string value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, string value)
		{
			switch (field)
			{
				case Field.ActualSerialNo:
					actualSerialNo = value;
					break;
				case Field.ActualPartBatchNo:
					actualPartBatchNo = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, DateTime? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, DateTime? value)
		{
			switch (field)
			{
				case Field.ActualExpiryDate:
					actualExpiryDate = value;
					break;
				case Field.ActualManufacturingDate:
					actualManufacturingDate = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, Guid? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, Guid? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override bool IsIdentity(int field)
		{
			return false;
		}

		#endregion Overriding / Public Members
	}
}
