//// Warning: Do not modify!
//// This file (VehicleCloseActionEntity.cs) has been auto-generated by PALMS Entity Generation Tool on 'Thursday, February 8, 2018' at '6:36:44 PM'
//// If modification is required, consider 'partial class'.

using System;
using System.Collections;
using System.Collections.Generic;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Actions
{
	[Serializable]
	public partial class VehicleCloseActionEntity : Entity
	{
		#region Enums

		public new enum Field
		{
			IsActive
			, OriginalVehicleNo
			, VehicleID
			, VehicleNo
			, VehicleStatusID
			, VehicleTypeID
			, VehicleTypeID_PackTypeCode
			, VehicleTypeID_PackTypeName
			, VehicleStatusID_PalmsStatusCode
			, VehicleStatusID_PalmsStatusName
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public bool? isActive;
		public string originalVehicleNo;
		public int? vehicleID;
		public string vehicleNo;
		public int? vehicleStatusID;
		public int? vehicleTypeID;
		public string vehicleTypeID_PackTypeCode;
		public string vehicleTypeID_PackTypeName;
		public string vehicleStatusID_PalmsStatusCode;
		public string vehicleStatusID_PalmsStatusName;

		#endregion Members

		#region Overriding / Public Members


		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.IsActive:
					return isActive;
				case Field.OriginalVehicleNo:
					return originalVehicleNo;
				case Field.VehicleID:
					return vehicleID;
				case Field.VehicleNo:
					return vehicleNo;
				case Field.VehicleStatusID:
					return vehicleStatusID;
				case Field.VehicleTypeID:
					return vehicleTypeID;
				case Field.VehicleTypeID_PackTypeCode:
					return vehicleTypeID_PackTypeCode;
				case Field.VehicleTypeID_PackTypeName:
					return vehicleTypeID_PackTypeName;
				case Field.VehicleStatusID_PalmsStatusCode:
					return vehicleStatusID_PalmsStatusCode;
				case Field.VehicleStatusID_PalmsStatusName:
					return vehicleStatusID_PalmsStatusName;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.IsActive:
					return typeof(bool?);
				case Field.OriginalVehicleNo:
					return typeof(string);
				case Field.VehicleID:
					return typeof(int?);
				case Field.VehicleNo:
					return typeof(string);
				case Field.VehicleStatusID:
					return typeof(int?);
				case Field.VehicleTypeID:
					return typeof(int?);
				case Field.VehicleTypeID_PackTypeCode:
					return typeof(string);
				case Field.VehicleTypeID_PackTypeName:
					return typeof(string);
				case Field.VehicleStatusID_PalmsStatusCode:
					return typeof(string);
				case Field.VehicleStatusID_PalmsStatusName:
					return typeof(string);

			}
			return null;
		}

		public override void SetValue(int field, bool? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, bool? value)
		{
			switch (field)
			{
				case Field.IsActive:
					isActive = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, long? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, long? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, int? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, int? value)
		{
			switch (field)
			{
				case Field.VehicleID:
					vehicleID = value;
					break;
				case Field.VehicleStatusID:
					vehicleStatusID = value;
					break;
				case Field.VehicleTypeID:
					vehicleTypeID = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, short? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, short? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, byte? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, byte? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, BitArray value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, BitArray value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, float? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, float? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, double? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, double? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, decimal? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, decimal? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, char? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, char? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, string value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, string value)
		{
			switch (field)
			{
				case Field.OriginalVehicleNo:
					originalVehicleNo = value;
					break;
				case Field.VehicleNo:
					vehicleNo = value;
					break;
				case Field.VehicleTypeID_PackTypeCode:
					vehicleTypeID_PackTypeCode = value;
					break;
				case Field.VehicleTypeID_PackTypeName:
					vehicleTypeID_PackTypeName = value;
					break;
				case Field.VehicleStatusID_PalmsStatusCode:
					vehicleStatusID_PalmsStatusCode = value;
					break;
				case Field.VehicleStatusID_PalmsStatusName:
					vehicleStatusID_PalmsStatusName = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, DateTime? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, DateTime? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, Guid? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, Guid? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override bool IsIdentity(int field)
		{
			return false;
		}

        //public override List<IEntityKey<Entity>> GetKeys()
        //{
        //    List<IEntityKey<Entity>> keys = new List<IEntityKey<Entity>>();

        //    keys.Add(GetPrimaryKey());

        //    return keys;
        //}

		#endregion Overriding / Public Members
	}
}
