//// Warning: Do not modify!
//// This file (PartStockForPartPickingLiftFromHandheldCustomSearchViewPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Thursday, March 2, 2017' at '6:24:21 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.PrimaryKeys
{
	[Serializable]
	public partial class PartStockForPartPickingLiftFromHandheldCustomSearchViewPrimaryKey : EntityKey<PartStockForPartPickingLiftFromHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			PrimaryCompanyID
			, WarehouseID
			, CostBucketID
			, PartStockID
			, TransactionTypeID
			, AllocationRuleLineNo
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? warehouseID;
		public int? costBucketID;
		public int? partStockID;
		public int? transactionTypeID;
		public int? allocationRuleLineNo;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.PartStockID:
					return partStockID;
				case Field.TransactionTypeID:
					return transactionTypeID;
				case Field.AllocationRuleLineNo:
					return allocationRuleLineNo;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.PartStockID:
					return typeof(int?);
				case Field.TransactionTypeID:
					return typeof(int?);
				case Field.AllocationRuleLineNo:
					return typeof(int?);
			}

			return null;
		}

		public override PartStockForPartPickingLiftFromHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new PartStockForPartPickingLiftFromHandheldCustomSearchViewEntity()
			{
				primaryCompanyID = primaryCompanyID
				, warehouseID = warehouseID
				, costBucketID = costBucketID
				, partStockID = partStockID
				, transactionTypeID = transactionTypeID
				, allocationRuleLineNo = allocationRuleLineNo
			};
		}

		public override string GetClassName()
		{
			return "PartStockForPartPickingLiftFromHandheldCustomSearchViewPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
