//// Warning: Do not modify!
//// This file (PartBinningInstructionHeaderForHandheldCustomSearchViewPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on '05 October 2012' at '17:31:29'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.PrimaryKeys
{
	[Serializable]
	public partial class PartBinningInstructionHeaderForHandheldCustomSearchViewPrimaryKey : EntityKey<PartBinningInstructionHeaderForHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			CostBucketID
			, WarehouseID
			, PrimaryCompanyID
			, BinningInstructionID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? costBucketID;
		public int? warehouseID;
		public int? primaryCompanyID;
		public int? binningInstructionID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return costBucketID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.BinningInstructionID:
					return binningInstructionID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.BinningInstructionID:
					return typeof(int?);
			}

			return null;
		}

		public override PartBinningInstructionHeaderForHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new PartBinningInstructionHeaderForHandheldCustomSearchViewEntity()
			{
				costBucketID = costBucketID
				, warehouseID = warehouseID
				, primaryCompanyID = primaryCompanyID
				, binningInstructionID = binningInstructionID
			};
		}

		public override string GetClassName()
		{
			return "PartBinningInstructionHeaderForHandheldCustomSearchViewPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
