//// Warning: Do not modify!
//// This file (SupplierCustomSearchViewPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on '27 September 2013' at '17:20:55'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.PrimaryKeys
{
	[Serializable]
	public partial class SupplierCustomSearchViewPrimaryKey : EntityKey<SupplierCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			PrimaryCompanyID
			, SupplierID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? supplierID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.SupplierID:
					return supplierID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.SupplierID:
					return typeof(int?);
			}

			return null;
		}

		public override SupplierCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new SupplierCustomSearchViewEntity()
			{
				primaryCompanyID = primaryCompanyID
				, supplierID = supplierID
			};
		}

		public override string GetClassName()
		{
			return "SupplierCustomSearchViewPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
