//// Warning: Do not modify!
//// This file (WeightCaptureForGateInwardCustomSearchViewEntity.cs) has been auto-generated by PALMS Entity Generation Tool on 'Wednesday, August 22, 2018' at '3:35:32 PM'
//// If modification is required, consider 'partial class'.

using System;
using System.Collections;
using System.Collections.Generic;
using Technoforte.PALMS.Entities.CustomSearchViews.PrimaryKeys;
using Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews
{
	[Serializable]
	public partial class WeightCaptureForGateInwardCustomSearchViewEntity : Entity
	{
		#region Enums

		public new enum Field
		{
			PartID
			, PartCode
			, PartName
			, StorageUOMID
			, DefaultPurchaseUOMID
			, DefaultPurchaseBillingUOMID
			, DefaultSalesUOMID
			, DefaultSalesBillingUOMID
			, IsKit
			, PartTypeID
			, IsExpirySensitive
			, IsSerialNumberTracked
			, MinimumFreeShelfLife
			, ShelfLifeUnit
			, MultiplicationFactor
			, TotalShelfLife
			, TotalShelfLifeUnit
			, IsTrackedByManufactureDate
			, IsUnderCycleCount
			, IsComponentPart
			, IsBatchSensitive
			, IsWeightRequired
			, StockBucketID
			, StockBucketName
			, StockBucketCode
			, PartBatchID
			, PartBatchNo
			, ManufacturingDate
			, ExpiryDate
			, SerialNo
			, IncomingWeight
			, GateInwardID
			, GateInwardNo
			, GateInwardLineNo
			, PartStockID
			, BucketQuantityInStorageUOM
			, LocationID
			, CumulativeLocationCode
			, PrimaryCompanyID
			, WarehouseID
			, CostBucketID
			, WarehousePrimaryCompanyID
			, UOMCode
			, WeightCaptureLotSize
			
			, _FieldCount
		}

		public enum UniqueKey
		{
			Default
		}

		#endregion Enums

		#region Members

		public int? partID;
		public string partCode;
		public string partName;
		public int? storageUOMID;
		public int? defaultPurchaseUOMID;
		public int? defaultPurchaseBillingUOMID;
		public int? defaultSalesUOMID;
		public int? defaultSalesBillingUOMID;
		public bool? isKit;
		public int? partTypeID;
		public bool? isExpirySensitive;
		public bool? isSerialNumberTracked;
		public int? minimumFreeShelfLife;
		public int? shelfLifeUnit;
		public decimal? multiplicationFactor;
		public int? totalShelfLife;
		public int? totalShelfLifeUnit;
		public bool? isTrackedByManufactureDate;
		public bool? isUnderCycleCount;
		public bool? isComponentPart;
		public bool? isBatchSensitive;
		public bool? isWeightRequired;
		public int? stockBucketID;
		public string stockBucketName;
		public string stockBucketCode;
		public int? partBatchID;
		public string partBatchNo;
		public DateTime? manufacturingDate;
		public DateTime? expiryDate;
		public string serialNo;
		public decimal? incomingWeight;
		public int? gateInwardID;
		public string gateInwardNo;
		public int? gateInwardLineNo;
		public int? partStockID;
		public decimal? bucketQuantityInStorageUOM;
		public int? locationID;
		public string cumulativeLocationCode;
		public int? primaryCompanyID;
		public int? warehouseID;
		public int? costBucketID;
		public int? warehousePrimaryCompanyID;
		public string uOMCode;
		public int? weightCaptureLotSize;

		#endregion Members

		#region Overriding / Public Members

		public override IEntityKey<Entity> GetPrimaryKey()
		{
			return (IEntityKey<Entity>)new WeightCaptureForGateInwardCustomSearchViewPrimaryKey()
			{
				warehouseID = (int)warehouseID
				, primaryCompanyID = (int)primaryCompanyID
				, costBucketID = (int)costBucketID
				, partStockID = (int)partStockID
				, partBatchID = (int)partBatchID
			};
		}

		public override IEntityKey<Entity> GetBlankPrimaryKey()
		{
			return (IEntityKey<Entity>)new WeightCaptureForGateInwardCustomSearchViewPrimaryKey();
		}

		public override IEntityKey<Entity> GetUniqueKey(string uniqueKey)
		{
			if (uniqueKey == "")
			{
				uniqueKey = "Default";
			}

			return (IEntityKey<Entity>)GetUniqueKey((UniqueKey)Enum.Parse(typeof(UniqueKey), uniqueKey,false));
		}

		public EntityKey<WeightCaptureForGateInwardCustomSearchViewEntity> GetUniqueKey(UniqueKey uniqueKey)
		{
			switch (uniqueKey)
			{
				case UniqueKey.Default:
					return new WeightCaptureForGateInwardCustomSearchViewUniqueKey()
					{
						warehouseID = (int?)warehouseID
						, primaryCompanyID = (int?)primaryCompanyID
						, costBucketID = (int?)costBucketID
						, partStockID = (int?)partStockID
						, partBatchID = (int?)partBatchID
					};
			}

			return null;
		}

		public override IEntityKey<Entity> GetBlankUniqueKey(string uniqueKey)
		{
			if (uniqueKey == "")
			{
				uniqueKey = "Default";
			}

			return (IEntityKey<Entity>)GetBlankUniqueKey((UniqueKey)Enum.Parse(typeof(UniqueKey), uniqueKey, false));
		}

		public EntityKey<WeightCaptureForGateInwardCustomSearchViewEntity> GetBlankUniqueKey(UniqueKey uniqueKey)
		{
			switch (uniqueKey)
			{
				case UniqueKey.Default:
					return new WeightCaptureForGateInwardCustomSearchViewUniqueKey();
			}

			return null;
		}

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PartID:
					return partID;
				case Field.PartCode:
					return partCode;
				case Field.PartName:
					return partName;
				case Field.StorageUOMID:
					return storageUOMID;
				case Field.DefaultPurchaseUOMID:
					return defaultPurchaseUOMID;
				case Field.DefaultPurchaseBillingUOMID:
					return defaultPurchaseBillingUOMID;
				case Field.DefaultSalesUOMID:
					return defaultSalesUOMID;
				case Field.DefaultSalesBillingUOMID:
					return defaultSalesBillingUOMID;
				case Field.IsKit:
					return isKit;
				case Field.PartTypeID:
					return partTypeID;
				case Field.IsExpirySensitive:
					return isExpirySensitive;
				case Field.IsSerialNumberTracked:
					return isSerialNumberTracked;
				case Field.MinimumFreeShelfLife:
					return minimumFreeShelfLife;
				case Field.ShelfLifeUnit:
					return shelfLifeUnit;
				case Field.MultiplicationFactor:
					return multiplicationFactor;
				case Field.TotalShelfLife:
					return totalShelfLife;
				case Field.TotalShelfLifeUnit:
					return totalShelfLifeUnit;
				case Field.IsTrackedByManufactureDate:
					return isTrackedByManufactureDate;
				case Field.IsUnderCycleCount:
					return isUnderCycleCount;
				case Field.IsComponentPart:
					return isComponentPart;
				case Field.IsBatchSensitive:
					return isBatchSensitive;
				case Field.IsWeightRequired:
					return isWeightRequired;
				case Field.StockBucketID:
					return stockBucketID;
				case Field.StockBucketName:
					return stockBucketName;
				case Field.StockBucketCode:
					return stockBucketCode;
				case Field.PartBatchID:
					return partBatchID;
				case Field.PartBatchNo:
					return partBatchNo;
				case Field.ManufacturingDate:
					return manufacturingDate;
				case Field.ExpiryDate:
					return expiryDate;
				case Field.SerialNo:
					return serialNo;
				case Field.IncomingWeight:
					return incomingWeight;
				case Field.GateInwardID:
					return gateInwardID;
				case Field.GateInwardNo:
					return gateInwardNo;
				case Field.GateInwardLineNo:
					return gateInwardLineNo;
				case Field.PartStockID:
					return partStockID;
				case Field.BucketQuantityInStorageUOM:
					return bucketQuantityInStorageUOM;
				case Field.LocationID:
					return locationID;
				case Field.CumulativeLocationCode:
					return cumulativeLocationCode;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
				case Field.UOMCode:
					return uOMCode;
				case Field.WeightCaptureLotSize:
					return weightCaptureLotSize;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PartID:
					return typeof(int?);
				case Field.PartCode:
					return typeof(string);
				case Field.PartName:
					return typeof(string);
				case Field.StorageUOMID:
					return typeof(int?);
				case Field.DefaultPurchaseUOMID:
					return typeof(int?);
				case Field.DefaultPurchaseBillingUOMID:
					return typeof(int?);
				case Field.DefaultSalesUOMID:
					return typeof(int?);
				case Field.DefaultSalesBillingUOMID:
					return typeof(int?);
				case Field.IsKit:
					return typeof(bool?);
				case Field.PartTypeID:
					return typeof(int?);
				case Field.IsExpirySensitive:
					return typeof(bool?);
				case Field.IsSerialNumberTracked:
					return typeof(bool?);
				case Field.MinimumFreeShelfLife:
					return typeof(int?);
				case Field.ShelfLifeUnit:
					return typeof(int?);
				case Field.MultiplicationFactor:
					return typeof(decimal?);
				case Field.TotalShelfLife:
					return typeof(int?);
				case Field.TotalShelfLifeUnit:
					return typeof(int?);
				case Field.IsTrackedByManufactureDate:
					return typeof(bool?);
				case Field.IsUnderCycleCount:
					return typeof(bool?);
				case Field.IsComponentPart:
					return typeof(bool?);
				case Field.IsBatchSensitive:
					return typeof(bool?);
				case Field.IsWeightRequired:
					return typeof(bool?);
				case Field.StockBucketID:
					return typeof(int?);
				case Field.StockBucketName:
					return typeof(string);
				case Field.StockBucketCode:
					return typeof(string);
				case Field.PartBatchID:
					return typeof(int?);
				case Field.PartBatchNo:
					return typeof(string);
				case Field.ManufacturingDate:
					return typeof(DateTime?);
				case Field.ExpiryDate:
					return typeof(DateTime?);
				case Field.SerialNo:
					return typeof(string);
				case Field.IncomingWeight:
					return typeof(decimal?);
				case Field.GateInwardID:
					return typeof(int?);
				case Field.GateInwardNo:
					return typeof(string);
				case Field.GateInwardLineNo:
					return typeof(int?);
				case Field.PartStockID:
					return typeof(int?);
				case Field.BucketQuantityInStorageUOM:
					return typeof(decimal?);
				case Field.LocationID:
					return typeof(int?);
				case Field.CumulativeLocationCode:
					return typeof(string);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
				case Field.UOMCode:
					return typeof(string);
				case Field.WeightCaptureLotSize:
					return typeof(int?);

			}
			return null;
		}

		public override void SetValue(int field, bool? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, bool? value)
		{
			switch (field)
			{
				case Field.IsKit:
					isKit = value;
					break;
				case Field.IsExpirySensitive:
					isExpirySensitive = value;
					break;
				case Field.IsSerialNumberTracked:
					isSerialNumberTracked = value;
					break;
				case Field.IsTrackedByManufactureDate:
					isTrackedByManufactureDate = value;
					break;
				case Field.IsUnderCycleCount:
					isUnderCycleCount = value;
					break;
				case Field.IsComponentPart:
					isComponentPart = value;
					break;
				case Field.IsBatchSensitive:
					isBatchSensitive = value;
					break;
				case Field.IsWeightRequired:
					isWeightRequired = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, long? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, long? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, int? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, int? value)
		{
			switch (field)
			{
				case Field.PartID:
					partID = value;
					break;
				case Field.StorageUOMID:
					storageUOMID = value;
					break;
				case Field.DefaultPurchaseUOMID:
					defaultPurchaseUOMID = value;
					break;
				case Field.DefaultPurchaseBillingUOMID:
					defaultPurchaseBillingUOMID = value;
					break;
				case Field.DefaultSalesUOMID:
					defaultSalesUOMID = value;
					break;
				case Field.DefaultSalesBillingUOMID:
					defaultSalesBillingUOMID = value;
					break;
				case Field.PartTypeID:
					partTypeID = value;
					break;
				case Field.MinimumFreeShelfLife:
					minimumFreeShelfLife = value;
					break;
				case Field.ShelfLifeUnit:
					shelfLifeUnit = value;
					break;
				case Field.TotalShelfLife:
					totalShelfLife = value;
					break;
				case Field.TotalShelfLifeUnit:
					totalShelfLifeUnit = value;
					break;
				case Field.StockBucketID:
					stockBucketID = value;
					break;
				case Field.PartBatchID:
					partBatchID = value;
					break;
				case Field.GateInwardID:
					gateInwardID = value;
					break;
				case Field.GateInwardLineNo:
					gateInwardLineNo = value;
					break;
				case Field.PartStockID:
					partStockID = value;
					break;
				case Field.LocationID:
					locationID = value;
					break;
				case Field.PrimaryCompanyID:
					primaryCompanyID = value;
					break;
				case Field.WarehouseID:
					warehouseID = value;
					break;
				case Field.CostBucketID:
					costBucketID = value;
					break;
				case Field.WarehousePrimaryCompanyID:
					warehousePrimaryCompanyID = value;
					break;
				case Field.WeightCaptureLotSize:
					weightCaptureLotSize = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, short? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, short? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, byte? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, byte? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, BitArray value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, BitArray value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, float? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, float? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, double? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, double? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, decimal? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, decimal? value)
		{
			switch (field)
			{
				case Field.MultiplicationFactor:
					multiplicationFactor = value;
					break;
				case Field.IncomingWeight:
					incomingWeight = value;
					break;
				case Field.BucketQuantityInStorageUOM:
					bucketQuantityInStorageUOM = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, char? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, char? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override void SetValue(int field, string value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, string value)
		{
			switch (field)
			{
				case Field.PartCode:
					partCode = value;
					break;
				case Field.PartName:
					partName = value;
					break;
				case Field.StockBucketName:
					stockBucketName = value;
					break;
				case Field.StockBucketCode:
					stockBucketCode = value;
					break;
				case Field.PartBatchNo:
					partBatchNo = value;
					break;
				case Field.SerialNo:
					serialNo = value;
					break;
				case Field.GateInwardNo:
					gateInwardNo = value;
					break;
				case Field.CumulativeLocationCode:
					cumulativeLocationCode = value;
					break;
				case Field.UOMCode:
					uOMCode = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, DateTime? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, DateTime? value)
		{
			switch (field)
			{
				case Field.ManufacturingDate:
					manufacturingDate = value;
					break;
				case Field.ExpiryDate:
					expiryDate = value;
					break;
				default:
					break;
			}
		}

		public override void SetValue(int field, Guid? value)
		{
			SetValue((Field)field, value);
		}

		public void SetValue(Field field, Guid? value)
		{
			switch (field)
			{
				default:
					break;
			}
		}

		public override bool IsIdentity(int field)
		{
			return false;
		}

		#endregion Overriding / Public Members
	}
}
