//// Warning: Do not modify!
//// This file (CustomerPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, March 21, 2017' at '4:24:09 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class CustomerPrimaryKey : EntityKey<CustomerEntity>
	{
		#region Enums

		public enum Field
		{
			CustomerID
			, PrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? customerID;
		public int? primaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CustomerID:
					return customerID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CustomerID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override CustomerEntity GetBlankEntityWithKey()
		{
			return new CustomerEntity()
			{
				customerID = customerID
				, primaryCompanyID = primaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "CustomerPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
