//// Warning: Do not modify!
//// This file (CycleCountInstructionLinePrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Friday, June 1, 2018' at '10:53:59 AM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class CycleCountInstructionLinePrimaryKey : EntityKey<CycleCountInstructionLineEntity>
	{
		#region Enums

		public enum Field
		{
			CostBucketID
			, CycleCountInstructionID
			, PartID
			, PrimaryCompanyID
			, WarehouseID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? costBucketID;
		public int? cycleCountInstructionID;
		public int? partID;
		public int? primaryCompanyID;
		public int? warehouseID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return costBucketID;
				case Field.CycleCountInstructionID:
					return cycleCountInstructionID;
				case Field.PartID:
					return partID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return typeof(int?);
				case Field.CycleCountInstructionID:
					return typeof(int?);
				case Field.PartID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
			}

			return null;
		}

		public override CycleCountInstructionLineEntity GetBlankEntityWithKey()
		{
			return new CycleCountInstructionLineEntity()
			{
				costBucketID = costBucketID
				, cycleCountInstructionID = cycleCountInstructionID
				, partID = partID
				, primaryCompanyID = primaryCompanyID
				, warehouseID = warehouseID
			};
		}

		public override string GetClassName()
		{
			return "CycleCountInstructionLinePrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
