//// Warning: Do not modify!
//// This file (CycleCountInstructionResultPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Thursday, October 27, 2016' at '11:04:11 AM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class CycleCountInstructionResultPrimaryKey : EntityKey<CycleCountInstructionResultEntity>
	{
		#region Enums

		public enum Field
		{
			CostBucketID
			, CycleCountInstructionResultID
			, PrimaryCompanyID
			, WarehouseID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? costBucketID;
		public int? cycleCountInstructionResultID;
		public int? primaryCompanyID;
		public int? warehouseID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return costBucketID;
				case Field.CycleCountInstructionResultID:
					return cycleCountInstructionResultID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CostBucketID:
					return typeof(int?);
				case Field.CycleCountInstructionResultID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
			}

			return null;
		}

		public override CycleCountInstructionResultEntity GetBlankEntityWithKey()
		{
			return new CycleCountInstructionResultEntity()
			{
				costBucketID = costBucketID
				, cycleCountInstructionResultID = cycleCountInstructionResultID
				, primaryCompanyID = primaryCompanyID
				, warehouseID = warehouseID
			};
		}

		public override string GetClassName()
		{
			return "CycleCountInstructionResultPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
