//// Warning: Do not modify!
//// This file (EnumerationPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on '12 January 2012' at '16:40:13'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class EnumerationPrimaryKey : EntityKey<EnumerationEntity>
	{
		#region Enums

		public enum Field
		{
			EnumerationID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? enumerationID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.EnumerationID:
					return enumerationID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.EnumerationID:
					return typeof(int?);
			}

			return null;
		}

		public override EnumerationEntity GetBlankEntityWithKey()
		{
			return new EnumerationEntity()
			{
				enumerationID = enumerationID
			};
		}

		public override string GetClassName()
		{
			return "EnumerationPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
