//// Warning: Do not modify!
//// This file (PartCategoryPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Thursday, July 7, 2016' at '9:20:10 AM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class PartCategoryPrimaryKey : EntityKey<PartCategoryEntity>
	{
		#region Enums

		public enum Field
		{
			PartCategoryID
			, PrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? partCategoryID;
		public int? primaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PartCategoryID:
					return partCategoryID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PartCategoryID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override PartCategoryEntity GetBlankEntityWithKey()
		{
			return new PartCategoryEntity()
			{
				partCategoryID = partCategoryID
				, primaryCompanyID = primaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "PartCategoryPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
