//// Warning: Do not modify!
//// This file (PartBatchPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on '18 September 2014' at '12:03:04'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class PartBatchPrimaryKey : EntityKey<PartBatchEntity>
	{
		#region Enums

		public enum Field
		{
			PartBatchID
			, PrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? partBatchID;
		public int? primaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PartBatchID:
					return partBatchID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PartBatchID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override PartBatchEntity GetBlankEntityWithKey()
		{
			return new PartBatchEntity()
			{
				partBatchID = partBatchID
				, primaryCompanyID = primaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "PartBatchPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
