//// Warning: Do not modify!
//// This file (WarehousePrimaryCompanyMappingPrimaryKey.cs) has been auto-generated by PALMS Entity Generation Tool on '26 February 2013' at '09:51:23'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.Views.PrimaryKeys
{
	[Serializable]
	public partial class WarehousePrimaryCompanyMappingPrimaryKey : EntityKey<WarehousePrimaryCompanyMappingEntity>
	{
		#region Enums

		public enum Field
		{
			PrimaryCompanyID
			, WarehouseID
			, WarehousePrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? warehouseID;
		public int? warehousePrimaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override WarehousePrimaryCompanyMappingEntity GetBlankEntityWithKey()
		{
			return new WarehousePrimaryCompanyMappingEntity()
			{
				primaryCompanyID = primaryCompanyID
				, warehouseID = warehouseID
				, warehousePrimaryCompanyID = warehousePrimaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "WarehousePrimaryCompanyMappingPrimaryKey";
		}

		#endregion Overriding / Public Members
	}
}
