//// Warning: Do not modify!
//// This file (CycleCountHandheldCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Monday, May 7, 2018' at '5:15:23 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class CycleCountHandheldCustomSearchViewUniqueKey : EntityKey<CycleCountHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			WarehouseID
			, PrimaryCompanyID
			, CostBucketID
			, CycleCountInstructionID
			, LocationID
			, PartID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? warehouseID;
		public int? primaryCompanyID;
		public int? costBucketID;
		public int? cycleCountInstructionID;
		public int? locationID;
		public int? partID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return warehouseID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.CycleCountInstructionID:
					return cycleCountInstructionID;
				case Field.LocationID:
					return locationID;
				case Field.PartID:
					return partID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.CycleCountInstructionID:
					return typeof(int?);
				case Field.LocationID:
					return typeof(int?);
				case Field.PartID:
					return typeof(int?);
			}

			return null;
		}

		public override CycleCountHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new CycleCountHandheldCustomSearchViewEntity()
			{
				warehouseID = warehouseID
				, primaryCompanyID = primaryCompanyID
				, costBucketID = costBucketID
				, cycleCountInstructionID = cycleCountInstructionID
				, locationID = locationID
				, partID = partID
			};
		}

		public override string GetClassName()
		{
			return "CycleCountHandheldCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
