//// Warning: Do not modify!
//// This file (CycleCountInstructionResultCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, October 25, 2016' at '10:10:14 AM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class CycleCountInstructionResultCustomSearchViewUniqueKey : EntityKey<CycleCountInstructionResultCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			CycleCountInstructionID
			, WarehouseID
			, PrimaryCompanyID
			, CostBucketID
			, LocationID
			, PartID
			, WarehousePrimaryCompanyID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? cycleCountInstructionID;
		public int? warehouseID;
		public int? primaryCompanyID;
		public int? costBucketID;
		public int? locationID;
		public int? partID;
		public int? warehousePrimaryCompanyID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.CycleCountInstructionID:
					return cycleCountInstructionID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.LocationID:
					return locationID;
				case Field.PartID:
					return partID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.CycleCountInstructionID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.LocationID:
					return typeof(int?);
				case Field.PartID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
			}

			return null;
		}

		public override CycleCountInstructionResultCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new CycleCountInstructionResultCustomSearchViewEntity()
			{
				cycleCountInstructionID = cycleCountInstructionID
				, warehouseID = warehouseID
				, primaryCompanyID = primaryCompanyID
				, costBucketID = costBucketID
				, locationID = locationID
				, partID = partID
				, warehousePrimaryCompanyID = warehousePrimaryCompanyID
			};
		}

		public override string GetClassName()
		{
			return "CycleCountInstructionResultCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
