//// Warning: Do not modify!
//// This file (PartWithStorageUOMAndBillingUOMCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Thursday, December 28, 2017' at '11:39:50 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class PartWithStorageUOMAndBillingUOMCustomSearchViewUniqueKey : EntityKey<PartWithStorageUOMAndBillingUOMCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			PrimaryCompanyID
			, PartID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? partID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.PartID:
					return partID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.PartID:
					return typeof(int?);
			}

			return null;
		}

		public override PartWithStorageUOMAndBillingUOMCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new PartWithStorageUOMAndBillingUOMCustomSearchViewEntity()
			{
				primaryCompanyID = primaryCompanyID
				, partID = partID
			};
		}

		public override string GetClassName()
		{
			return "PartWithStorageUOMAndBillingUOMCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
