//// Warning: Do not modify!
//// This file (QuickTransferFromHandheldCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, January 2, 2018' at '5:25:22 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class QuickTransferFromHandheldCustomSearchViewUniqueKey : EntityKey<QuickTransferFromHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			PrimaryCompanyID
			, WarehouseID
			, CostBucketID
			, PartStockID
			, PartBatchID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? primaryCompanyID;
		public int? warehouseID;
		public int? costBucketID;
		public int? partStockID;
		public int? partBatchID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.WarehouseID:
					return warehouseID;
				case Field.CostBucketID:
					return costBucketID;
				case Field.PartStockID:
					return partStockID;
				case Field.PartBatchID:
					return partBatchID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.WarehouseID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
				case Field.PartStockID:
					return typeof(int?);
				case Field.PartBatchID:
					return typeof(int?);
			}

			return null;
		}

		public override QuickTransferFromHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new QuickTransferFromHandheldCustomSearchViewEntity()
			{
				primaryCompanyID = primaryCompanyID
				, warehouseID = warehouseID
				, costBucketID = costBucketID
				, partStockID = partStockID
				, partBatchID = partBatchID
			};
		}

		public override string GetClassName()
		{
			return "QuickTransferFromHandheldCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
