//// Warning: Do not modify!
//// This file (StockBucketFromHandheldCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, December 29, 2015' at '5:06:47 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class StockBucketFromHandheldCustomSearchViewUniqueKey : EntityKey<StockBucketFromHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			StockBucketID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? stockBucketID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.StockBucketID:
					return stockBucketID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.StockBucketID:
					return typeof(int?);
			}

			return null;
		}

		public override StockBucketFromHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new StockBucketFromHandheldCustomSearchViewEntity()
			{
				stockBucketID = stockBucketID
			};
		}

		public override string GetClassName()
		{
			return "StockBucketFromHandheldCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
