//// Warning: Do not modify!
//// This file (StockTakingHandheldCustomSearchViewUniqueKey.cs) has been auto-generated by PALMS Entity Generation Tool on 'Tuesday, December 15, 2015' at '5:10:38 PM'
//// If modification is required, consider 'partial class'.

using System;

#pragma warning disable 1591

namespace Technoforte.PALMS.Entities.CustomSearchViews.UniqueKeys
{
	[Serializable]
	public partial class StockTakingHandheldCustomSearchViewUniqueKey : EntityKey<StockTakingHandheldCustomSearchViewEntity>
	{
		#region Enums

		public enum Field
		{
			WarehouseID
			, WarehousePrimaryCompanyID
			, LocationID
			, StockTakingInstructionID
			, PrimaryCompanyID
			, CostBucketID
			
			, _FieldCount
		}

		#endregion Enums

		#region Members

		public int? warehouseID;
		public int? warehousePrimaryCompanyID;
		public int? locationID;
		public int? stockTakingInstructionID;
		public int? primaryCompanyID;
		public int? costBucketID;

		#endregion Members

		#region Overriding / Public Members

		public override int GetFieldCount()
		{
			return (int)Field._FieldCount;
		}

		public override object GetValue(int field)
		{
			return GetValue((Field)field);
		}

		public object GetValue(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return warehouseID;
				case Field.WarehousePrimaryCompanyID:
					return warehousePrimaryCompanyID;
				case Field.LocationID:
					return locationID;
				case Field.StockTakingInstructionID:
					return stockTakingInstructionID;
				case Field.PrimaryCompanyID:
					return primaryCompanyID;
				case Field.CostBucketID:
					return costBucketID;
			}

			return null;
		}

		public override string GetFieldName(int field)
		{
			return GetFieldName((Field)field);
		}

		public string GetFieldName(Field field)
		{
			return field.ToString();
		}

		public override Type GetType(int field)
		{
			return GetType((Field)field);
		}

		public Type GetType(Field field)
		{
			switch (field)
			{
				case Field.WarehouseID:
					return typeof(int?);
				case Field.WarehousePrimaryCompanyID:
					return typeof(int?);
				case Field.LocationID:
					return typeof(int?);
				case Field.StockTakingInstructionID:
					return typeof(int?);
				case Field.PrimaryCompanyID:
					return typeof(int?);
				case Field.CostBucketID:
					return typeof(int?);
			}

			return null;
		}

		public override StockTakingHandheldCustomSearchViewEntity GetBlankEntityWithKey()
		{
			return new StockTakingHandheldCustomSearchViewEntity()
			{
				warehouseID = warehouseID
				, warehousePrimaryCompanyID = warehousePrimaryCompanyID
				, locationID = locationID
				, stockTakingInstructionID = stockTakingInstructionID
				, primaryCompanyID = primaryCompanyID
				, costBucketID = costBucketID
			};
		}

		public override string GetClassName()
		{
			return "StockTakingHandheldCustomSearchViewUniqueKey";
		}

		#endregion Overriding / Public Members
	}
}
